services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile_app
    command: |
      bash -c '
      while !</dev/tcp/db/5432; do sleep 1; done; 
      alembic upgrade head
      uvicorn src.app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
      '
    ports:
      - 8000:8000
    env_file:
      - src/app/.env
    # local for uvicorn --reload
    volumes:
      - ./src/app:/opt/src/app


  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - src/app/.env

volumes:
  postgres_data: